export const WeatherActionTypes = {
  SET_UNIT: 'SET_UNIT',
  QUERY_DATA_START: 'QUERY_DATA_START',
  QUERY_DATA_SUCCESS: 'QUERY_DATA_SUCCESS',
  QUERY_DATA_FAILURE: 'QUERY_DATA_FAILURE',
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
  INIT_FETCH_DATA_START: 'INIT_FETCH_DATA_START',
  GET_USER_GEO_START: 'GET_USER_GEO_START',
  GET_USER_GEO_FAILURE: 'GET_USER_GEO_FAILURE',
  CLEAR_ERROR: 'CLEAR_ERROR',
}

export const UnitTypes = {
  Celsius: 'Celsius',
  Fahrenheit: 'Fahrenheit'
}